#!/usr/bin/env bash
# Installs nginx server and configure it based on the requirements provided
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
