#!/usr/bin/env bash
# Script that installs nginx web server and configures
# it based on the  requirements.

# update package list
apt-get update

# install nginx web server
apt-get install -y nginx

# configure server to listen to port: 80
ufw allow 'Nginx HTTP'

# add content  to index.html
echo "Hello World!" > /var/www/html/index.html

# start nginx
service nginx start
