#!/usr/bin/env bash
# Configure nginx, add custom nginx response header
# The custom header `X-Served-By` will identify the server that is handling the request.

hostname=$(hostname)

sed -i "s/server_name _;/server_name _;\n\tadd_header X-Served-By $hostname;/" /etc/nginx/sites-enabled/default

sudo service nginx restart
