#!/usr/bin/env bash
# Script installs and configure HAproxy on your lb-01 server.
# Requirements -- config
#   Configure HAproxy so that it send traffic to web-01 and web-02
#   Distribute requests using a roundrobin algorithm
#   Make sure that HAproxy can be managed via an init script
#   Make sure that your servers are configured with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02.

# update package manager
sudo apt-get update

# install haproxy
sudo apt-get -y install haproxy

# edit haproxy config file
server_config=\
"
frontend dean_frontend
	bind *:80
	mode http
	timeout client 30s
	default_backend dean_backend
backend dean_backend
	balance roundrobin
	mode http
	timeout connect 5s
	timeout server 30s
	server 307515-web-01 52.4.1.217:80 check
	server 307515-web-02 35.174.213.249:80 check

"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# config haproxy to be managed by an init script
echo  "ENABLED=1" | sudo tee -a /etc/default/haproxy

# start haproxy
sudo service haproxy start
