#!/usr/bin/env bash
# Script create a file '/var/run/myscript.pid' containing its PID
# displays 'To infinity and beyond' indefinitely
# displays 'I hate the kill command' when receiving a SIGTERM signal
# displays 'Y U no love me?!' when receiving a SIGINT signal
# delete the file created and terminate program when receiving a SIGQUIT or SIGTERM

terminator() {
    rm /var/run/myscript.pid;
    exit;
}

trap 'echo "I hate the kill command" && terminator' SIGTERM;
trap 'echo "Y U no love me?!"' SIGINT;
trap 'terminator' SIGQUIT;

echo "$$" > /var/run/myscript.pid;

while true;
do
    echo "To infinity and beyond";
    sleep 2;
done    
