#!/usr/bin/env bash
# Displays 'To infinite and beyond' indefinitely
# With a sleep 2 in between each iteration
# 'I am invincible!!!' when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM;

while true;
do
    echo "To infinite and beyond"
    sleep 2
done