#!/usr/bin/env bash
# Writes 'I am a live!' indefinitely to a file '/tmp/my_process'
# between every message, program should pause for 2 seconds

while true
do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
