#!/usr/bin/env bash
# Displays numbers from 1 to 100
# displays "FizzBuzz" when numbers is a multiple of 3 and 5
# displays "Fizz" when the number is a multiple 3
# displays "buzz" when the number is a multiple 5
# otherwise display the number
# display in a list format

i=1
while [ "$i" -le 100 ]
do
    if [[ $((i%3)) -eq 0 && $((i%5)) -eq 0 ]]
    then
        echo "FizzBuzz"
    elif [[ $((i%3)) -eq 0 ]]
    then
        echo "Fizz"
    elif [[ $((i%5)) -eq 0 ]]
    then
        echo "Buzz"
    else
        echo "$i"
    fi
    (( i++ ))
done