#!/usr/bin/env bash
# Script that displays numbers from 1 to 100. Displays FizzBuzz if number
# is a multiple of 3 and 5, Fizz if is a multiple of 3 or Buzz if it is a multiple of 5.

i=1

while [ $i -le 100 ];
do
    if [[ $(( i % 3 )) -eq 0 && $(( i % 5 )) -eq 0 ]]
    then
        echo "FizzBuzz"

    elif [ $(( i % 3 )) -eq 0 ]
    then
        echo "Fizz"

    elif [ $(( i % 5 )) -eq  0 ]
    then
        echo "Buzz"

    else
        echo $i

    fi
    (( i++ ))
done
