#!/usr/bin/env bash
# Script tells a story about the file "/etc/passwd"

filename="/etc/passwd"
while IFS=":" read -r username password user_id group_id _ home_directory shell
do
    echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $shell. $user_id's place is protected by the passcode $password, more info about the user here: $username"
done < "$filename"
