#!/usr/bin/env bash
#Displays "Best School" to stdout 10 time but for 9th time display "Hi" to stdout

i=0

while (( "$i" < 10 ))
do
    echo "Best School"
    if (( "$i" == 8 ))
    then
        echo "Hi"
    fi
    ((i++))
done
