#!/usr/bin/env bash
# Displays "bad luck" and "good luck" to stdout for 4th and 8th loop respectively
# and "Best School" for the rest of iteration until the 10th iteration.

i=1

while (( "$i" <= 10 ))
do
    if [ "$i" == 4 ]
    then
        echo "bad luck"
      elif [ "$i" == 8 ]
    then
          echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
