#!/usr/bin/env bash
# Displays to stdout "bad luck from china" for 4th loop, "bad luck from japan" for 9th loop and
# "bad luck from italy" for 17th loop and numbers for the rest of the loops.

i=1

while [ $i -le 20 ]
do
    echo $i
    case $i in
	4)
	    echo "bad luck from china"
	    ;;
	9)
	    echo "bad luck from japan"
	    ;;
	17)
	    echo "bad luck from italy"
	    ;;
    esac
    ((i++))
done
