#!/usr/bin/env bash
# Displays the time.
# Displays hours from 0 to 12 hours
# Displays minutes from 1 to 59 minutes

hour=0
while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minute=1
    while (( minute < 60 ))
    do
        echo "$minute"
	(( minute++ ))
    done
    (( hour++ ))
done