#!/usr/bin/env bash
# Displays:
#	The content of the current directory
#	In a list format
#	Where only the part of the name after the first dash is displayed.
# Must use for loop and do not display hidden files.

argv=$( ls )
for arg in $argv
do
    echo "$arg" | cut -d "-" -f 2;
done
