#!/usr/bin/env bash
# Script displays:
#    -> The content of the current directory
#    -> In a list format
#    -> Where only the part of the name after the first dash is displayed (refer to the example)
# Must use the for loop
# Do not display hidden files

contents=$(ls)
for content in $contents
do

    echo "$content" | cut -d "-" -f2
done
