#!/usr/bin/env bash
# Displays information about the school file
# Checks if file exists
# 	 prints school files exists (true) / does not exist (false)
# If file exists:
#    	 checks if file is empty
#	 checks if the file is a regular file
# If file not a regular one prints nothing

file="school"
if [ -e "$file" ]
then
    echo "school file exists"
    if [ -s "$file" ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f "$file" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
