#!/usr/bin/env bash
# Script configures an ubuntu server
# Requirements:
#    -> localhost resolves to 127.0.0.2
#    -> facebook.com resolves to 8.8.8.8.
#    -> The checker is running on Docker, so make sure to read this

cp /etc/hosts ~/hosts.new

sed -i "s/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost\n8.8.8.8 \tfacebook.com/" ~/hosts.new

cp ~/hosts.new /etc/hosts
