#!/usr/bin/env bash
# Script that run the whoami command under the user passed as an argument

if [ $# -eq 0 ]
then
  echo "Usage: <scipt_name> <user_name>"
  exit 1
fi

username=$1

sudo -u "$username" whoami;