#!/usr/bin/env bash
# Script fixes nginx server by changing to execute to nginx and listen on all active IPs on port 8080.

# change user to nginx
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf

# listen to port 8080
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default

chmod 644 /etc/nginx/nginx.conf

# restart nginx server
sudo -u nginx service nginx start
